version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - /home/mysql_data/logs:/var/log/mysql
      - /home/mysql_data/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --lower_case_table_names=1
    restart: always

  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    ports: 
      - 443:443
      - 80:80
      - 222:22
    restart: always
    volumes: 
      - /home/gitlab/config:/etc/gitlab
      - /home/gitlab/logs:/var/log/gitlab
      - /home/gitlab/data:/var/opt/gitlab
  
  cloud9:
    image: kdelfour/cloud9-docker
    container_name: cloud9
    volumes:
      - .:/workspace/
    restart: always
    ports:
      - 8011:80
      
  gitignore-io:
    image: gofunky/gitignore.io
    container_name: gitignore-io
    network_mode: host
    command: vapor run
  
  nginx:
    image: nginx
    container_name: nginx
    #ports: 
    # - 8080:8080
    network_mode: host
    volumes: 
      - /home/nginx/conf:/etc/nginx/conf.d
      - /home/nginx/logs:/var/log/nginx

  portainer:
    image: portainer/portainer
    container_name: portainer
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports: 
      - 2181:2181

  kafka:     # docker-compose up -d --scale kafka=2        # 可以进行扩展或缩容   
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.16.100.177          #本机ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis:5.0
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes: 
      - ./mongo_data:/data/db

  consul:
    image: consul
    container_name: consul
    ports:
      - 8500:8500
    volumes:
      - /etc/localtime:/etc/localtime
    restart: always
