version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - /home/mysql_data/logs:/var/log/mysql
      - /home/mysql_data/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: abc123
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --lower_case_table_names=1
    restart: always

  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    ports: 
      - 443:443
      - 80:80
      - 222:22
    restart: always
    volumes: 
      - /home/gitlab/config:/etc/gitlab
      - /home/gitlab/logs:/var/log/gitlab
      - /home/gitlab/data:/var/opt/gitlab
  
  cloud9:
    image: kdelfour/cloud9-docker
    container_name: cloud9
    volumes:
      - .:/workspace/
    restart: always
    ports:
      - 8011:80